---------------- start ----------------
Tue Sep 12 2017 16:13:57
max threads: 10
max memory: 10240 MB
time limit: 48 hours
gpu id(s): 2
---------------------------------------
passed parameters: testcomposite.py
2
2017-09-12 16:14:04.797975: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-12 16:14:04.798011: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-12 16:14:04.798017: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-09-12 16:14:04.798020: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-12 16:14:04.798024: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-09-12 16:14:05.250444: I tensorflow/core/common_runtime/gpu/gpu_device.cc:887] Found device 0 with properties: 
name: TITAN X (Pascal)
major: 6 minor: 1 memoryClockRate (GHz) 1.531
pciBusID 0000:83:00.0
Total memory: 11.90GiB
Free memory: 11.76GiB
2017-09-12 16:14:05.250496: I tensorflow/core/common_runtime/gpu/gpu_device.cc:908] DMA: 0 
2017-09-12 16:14:05.250502: I tensorflow/core/common_runtime/gpu/gpu_device.cc:918] 0:   Y 
2017-09-12 16:14:05.250511: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977] Creating TensorFlow device (/gpu:0) -> (device: 0, name: TITAN X (Pascal), pci bus id: 0000:83:00.0)
]0;IPython: autoencoder/testscriptsTraceback (most recent call last):
  File "testcomposite.py", line 42, in <module>
    test_outputs, test_l = sess.run([ae.outputs, ae.predict_loss], 
AttributeError: 'CompositeModel' object has no attribute 'outputs'
----------------- end -----------------
Tue Sep 12 2017 16:14:09
elapsed time: 000:00:11
---------------------------------------
